### PR TITLE
Fix fetching min_position from JSON response

### PR DESCRIPTION
**Pull request by SebastianMuszynski**
This PR should fix refetching the same collection of tweets all the time.

### CODE REVIEW

**Comment by CarbuncleOrigin** [comment]
I doesn't seem to work for me

**Comment by SimKaiLong** [comment]
@SebastianMuszynski , I've tried using this and it seemed to have remedied the issue when I limited query to 100 tweets. However, it doesn't seem to work when scraping larger amounts of data, still. i.e I changed the limit to 1000 tweets and there were duplicates again.

**Comment by Mehdzor** [comment]
Doesn't work for me. The issue not only in min_position

**Comment by mathil-uva** [comment]
Also doesn't work for me unfortunately

**Comment by hpiedcoq** [comment]
> Doesn't work for me. The issue not only in min_position

Yep... :/ On another request, similar to the first one, it stops. I've seen your report, thanks.

**Comment by pielco11** [comment]
There were a conflict with this PR in `twint/feed.py`

**Comment by SebastianMuszynski** [comment]
Closing this one as the fix has been introduced in: https://github.com/twintproject/twint/pull/252

**Pull request closed without merging**
