### PR TITLE
Fix repeating set of tweets load #250

### PR DESCRIPTION
**Pull request by Mehdzor**
The issue was in:
- User-Agent header
- Params encoding
- min_position mechanism change

### CODE REVIEW

**Comment by PiotrJZielinski** [comment]
Searching seems to be working fine, however --location flag causes error: 

> Request() missing 1 required positional argument: 'connector' [x] get.Tweet

My command:

`python3 Twint.py -s "#dieselgate" --since "2015-09-18" -o dataset.csv --csv --hashtags --stats --location`

**Comment by Mehdzor** [comment]
@PiotrJZielinski It should be working now.

**Comment by PiotrJZielinski** [comment]
Thanks! Indeed it does. Minor issue: once in a while 

> 'NoneType' object has no attribute 'find' [x] get.Tweet

pops in throughout tweets fetching.

**Comment by Mehdzor** [comment]
This is probably related to empty twitter response issue. Should be fixed soon after I believe.

**Comment by PiotrJZielinski** [comment]
@Mehdzor bad news, I waited for my code to execute and it stopped fetching after sth like ~10k of tweets. No error message, just finished job. I've been using same command as in first post. Am I doing something wrong?

**Comment by Mehdzor** [comment]
This is still about empty response. Sometimes twitter returns empty response and it is considered as an end of the data. It will be fixed soon but not in this PR.

**Comment by Mehdzor** [comment]
It is being tested right now.

**Comment by LaurenDahlin** [comment]
For some tweets I'm also getting 
`'NoneType' object has no attribute 'find' [x] get.Tweet `
and using Profile() for a username doesn't get full history. I updated from pull request #271 thinking that might fix it, but no dice. Should I file a new bug report or is this the same issue?

**Comment by pielco11** [comment]
@LaurenDahlin I merged #271 as patch for this kind of errors, please update your Twint package with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint` and let us know if the error comes again, if so, please provide us your query and we will investigate

**Pull request merged**
