### PR TITLE
Update no-more-tweets logic

### PR DESCRIPTION
**Pull request by debugzxcv**
cmd: `twint -s 'since:2019-01-26 until:2019-01-27 "kanadero" OR "kana-dero"'`
before this update: 4 tweets
after this update: 38 tweets

### CODE REVIEW

**Comment by pielco11** [comment]
immagine

I tried your query with Twint as is, but I got 71 tweets

I do not know why your were having only 4 tweets

```
1089308559689412608 2019-01-27 00:46:13 CET <stray7>  http://moguravr.com : 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート  http://moguravr.com : 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート.  https://www.moguravr.com/1stlive-kana-dero-report/ … これは素晴らしいレポート
1089300951607914496 2019-01-27 00:15:59 CET <facet31> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート | ニコニコニュース  https://news.nicovideo.jp/watch/nw4730240 
1089278925920845824 2019-01-26 22:48:28 CET <izumino> ニコニコニュースに掲載されたページのほうが写真が大きく表示されて質感が高いことに気付いてしもうたのですが、こちらもよろしくお願いします  「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート | ニコニコニュース  https://news.nicovideo.jp/watch/nw4730240?news_ref=watch_50_nw4672014 …
1089218022894518272 2019-01-26 18:46:28 CET <yanioman> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrより
1089200842748489734 2019-01-26 17:38:11 CET <puraga999> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから
1089192531726819328 2019-01-26 17:05:10 CET <kukiwakame013> KANADEROの感動が今でも
1089190011369472000 2019-01-26 16:55:09 CET <wind_0180> 思い返せばKANA-DEROの感想に「やっぱ“““命””””なんですよね…」って言ったの本郷猛の「生命」と同レベルだったので伝わらなくて当然過ぎるな。
1089188539349127168 2019-01-26 16:49:18 CET <wind_0180> KANA-DEROが良かったことを伝えたかったのだが語彙が死んで小並感しか伝わらなかった😢
1089188266341879808 2019-01-26 16:48:13 CET <gurafa> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから
1089185113487728641 2019-01-26 16:35:41 CET <Z_Yugami> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから
1089175323873226752 2019-01-26 15:56:47 CET <clocknote> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrより
1089175026996174848 2019-01-26 15:55:36 CET <yeayehyeahe2015> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート | MoguLive - バーチャルを「楽しむ」ためのエンタメメディア  https://www.moguravr.com/1stlive-kana-dero-report/?utm_source=dlvr.it&utm_medium=twitter … pic.twitter.com/HhDQ56W2Wd
1089173799205986307 2019-01-26 15:50:44 CET <fuso_wot_vt> KANA-DEROの記事、文章を書く人はプロだなぁと実感した
1089170889533415425 2019-01-26 15:39:10 CET <Die_Hardluck> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから  思い出して、再び泣いた
1089170878942765056 2019-01-26 15:39:08 CET <pinf0rt> #記憶喪失のあなたに皆が教えてくれること 　 リズと青い鳥を観て 「ご主人様と呼びなさい」 　 ニルス 「百円貸してるんだけど…」 　 Kaede Higuchi 1stLIVE "KANA-DERO" 「おまえは下僕だ…   http://appli-maker.jp/analytic_apps/65495/results/215610014 …
1089164303968550912 2019-01-26 15:13:00 CET <ramshita> 朝にKANADEROのアーカイブも切れたしCD盤初聴きしたら楓色の日々、染まる季節が良すぎて危うく遅刻しかけた
1089161843212316674 2019-01-26 15:03:13 CET <minato_hy> KANA-DERO観たあとヤギ回観返すみたいな
1089153380344164353 2019-01-26 14:29:36 CET <karia> いっぞ！ / “「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート | MoguLive - バーチャルを「楽しむ」ためのエンタメメディア”  http://htn.to/TjtH6if 
1089151237080006656 2019-01-26 14:21:05 CET <pochi104> なんかKANA-DEROで描こうと思ったけどあっだめだ・・・って筆バキバキして不老不死描いた
1089150340291747840 2019-01-26 14:17:31 CET <izumino> “「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート | MoguLive - バーチャルを「楽しむ」ためのエンタメメディア”  http://htn.to/iDYrDn 
1089149600982695936 2019-01-26 14:14:34 CET <wakasennnin> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrから
1089149098710786048 2019-01-26 14:12:35 CET <hatena_hotentry> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート | MoguLive - バーチャルを「楽しむ」ためのエンタメメディア  pic.twitter.com/n0J0uYJXsp
1089148936311304195 2019-01-26 14:11:56 CET <tamamo2434> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrから
1089148405996085248 2019-01-26 14:09:50 CET <tell1732> りょ KANADEROの時の鯖でいいですかね？
1089146051750113284 2019-01-26 14:00:28 CET <animegazer> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live &#8220;KANA-DERO&#8221;レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr via @moguravr エモ
1089145269227114496 2019-01-26 13:57:22 CET <555Kea> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート – Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ …
1089145252538081280 2019-01-26 13:57:18 CET <LW_vtfan> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート  https://www.moguravr.com/1stlive-kana-dero-report/ …
1089140950683676672 2019-01-26 13:40:12 CET <tohken_ranbilis> KANA-DEROライブが良すぎてバーチャルアイドルー‼︎ってなってる。でろーん はバーチャルアイドルじゃないけど
1089140302907039744 2019-01-26 13:37:38 CET <konniini> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート  https://www.moguravr.com/1stlive-kana-dero-report/amp/ …
1089137200678109184 2019-01-26 13:25:18 CET <shibasay> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート – Mogura VR -  https://www.moguravr.com/1stlive-kana-dero-report/amp … : 愛が溢れてて素晴らしいレポート。
1089137127919562752 2019-01-26 13:25:01 CET <tsuto_terumi> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから
1089136168917184512 2019-01-26 13:21:12 CET <mens_trend> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート | MoguLive - バーチャルを「楽しむ」ためのエンタメメディア  http://bit.ly/2G5suVX  w
1089132163067346944 2019-01-26 13:05:17 CET <kf_yagara2489> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート – Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ …
1089129591367643136 2019-01-26 12:55:04 CET <ka_netsu> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート – Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ …
1089127229747953664 2019-01-26 12:45:41 CET <paip0__> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート – Mogura VR 魂のこもったレポート  https://www.moguravr.com/1stlive-kana-dero-report/ …
1089121525586771971 2019-01-26 12:23:01 CET <itoma___> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live &#8220;KANA-DERO&#8221;レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから  ほんとにKANADEROは最高のライブだったんだよなあ
1089117897530560514 2019-01-26 12:08:36 CET <gold_orger> KANADEROから2週間、でろーんの配信やにじくじの響鳴と最終回のサプライズ、ライブレポ·····何度感情になったか·····
1089116967225589760 2019-01-26 12:04:54 CET <gold_orger> KANADEROライブレポ、途中から感情抑えられなくなって読み進めらんなくなった···
1089115351642628097 2019-01-26 11:58:29 CET <spindrift64> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート | MoguLive - バーチャルを「楽しむ」ためのエンタメメディア  https://www.moguravr.com/1stlive-kana-dero-report/ …
1089115265294450688 2019-01-26 11:58:08 CET <MaLuqu_2434> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live &#8220;KANA-DERO&#8221;レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrより はぁ〜〜😭
1089114230085758977 2019-01-26 11:54:01 CET <riku_tazumi> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート  https://www.moguravr.com/1stlive-kana-dero-report/ … #にじさんじ #KANADERO
1089113987298484224 2019-01-26 11:53:03 CET <untakap36> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live &#8220;KANA-DERO&#8221;レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrより またライブが観たくなった。行きたくなった。
1089111250506633217 2019-01-26 11:42:11 CET <ryo_okami> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live &#8220;KANA-DERO&#8221;レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr 来自 @moguravr
1089109661117083648 2019-01-26 11:35:52 CET <tanji_y> これ、レポートの熱量がすごいな。ファクトを踏まえた上で主観に思い切り振っている。ちょっと真似できない。  「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート – Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ …
1089108714995380225 2019-01-26 11:32:06 CET <minato_hy> KANA-DEROの円盤まじではやくほし
1089108440486633474 2019-01-26 11:31:01 CET <mask0924> KANADERO見たい....
1089108018460004352 2019-01-26 11:29:20 CET <OilyPicy> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live "KANA-DERO"レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrから
1089105515001438208 2019-01-26 11:19:24 CET <Medr> V の者だとモニターの演出にもそれぞれの個性が出るのが面白いですね。  「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live ”KANA-DERO”レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから
1089104619735703552 2019-01-26 11:15:50 CET <uti_san> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート – Mogura VR 分かりやすく、かつライブの楽しさを最大限に引き出してる文章で良かった(。-∀-)  https://www.moguravr.com/1stlive-kana-dero-report/ …
1089104378512822273 2019-01-26 11:14:53 CET <STBONO> KANA-DERO 未だに余韻が残るくらい良いライブだったなぁー(*´ー｀*) 仕事中、響鳴をつい口ずさんでしまう 命に嫌われているで何回でも泣きたいからライブ映像売ってくれると良いなー(  ；∀；)
1089104105266507781 2019-01-26 11:13:47 CET <yurisyuna_> KANA-DERO
1089103659923693568 2019-01-26 11:12:01 CET <jyaafaru010> KANADEROの体験記事読んで泣きかけた
1089101838790479873 2019-01-26 11:04:47 CET <_Senarhythm_> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート – Mogura VR   https://www.moguravr.com/1stlive-kana-dero-report/ …
1089101093517316097 2019-01-26 11:01:49 CET <virtualkj1> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート  https://vtuber000.com/?p=81903  pic.twitter.com/QIRqLZ8IxJ
1089101063427248129 2019-01-26 11:01:42 CET <vtubersyuki> そういってたのか、後ろ方でよくきこえなかったけどイェェェェエェエイっていってたw #KANADERO  pic.twitter.com/YwPPBn66LX
1089100674095140865 2019-01-26 11:00:09 CET <Getetsu> MoguraVR、なんだこのKANA-DEROの全身全霊のレポート！？無茶苦茶いい記事だ。泣いた。
1089100025425088516 2019-01-26 10:57:35 CET <dotibi45> KANA-DEROもう2週間前なのね…
1089099514240065536 2019-01-26 10:55:33 CET <10V_tkc> Reading: 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live "KANA-DERO&"レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから
1089099462427856897 2019-01-26 10:55:20 CET <Cauchy_P> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート – Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ …
1089099187508019200 2019-01-26 10:54:15 CET <secretbox297> KANA-DERO見たくなるじゃん！
1089098301868204033 2019-01-26 10:50:44 CET <dada4386> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live &#8220;KANA-DERO&#8221;レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから
1089097710156894211 2019-01-26 10:48:23 CET <3dvrmobile> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート  http://3dvrmobile.com/?p=68415  pic.twitter.com/MWBODRyAQF
1089095322645610496 2019-01-26 10:38:53 CET <Tomy_2434> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live &#8220;KANA-DERO&#8221;レポート - Mogura VR  https://www.moguravr.com/1stlive-kana-dero-report/ … #moguravr @moguravrさんから  ガチなレポだ
1089093839279792129 2019-01-26 10:33:00 CET <MoguraVR> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live "KANA-DERO"レポート -  http://www.moguravr.com/1stlive-kana-dero-report/ … #VTuber #樋口楓 #にじさんじ
1089093449838546944 2019-01-26 10:31:27 CET <Vtuber_info_> 「命」を運ぶキセキ。バーチャルライバー・樋口楓1st Live “KANA-DERO”レポート｜VTuber 最新ニュース一覧 – Mogura VR  https://vtuber.5chmap.com/?twi&id=2025  #VTuber
1089082376917966850 2019-01-26 09:47:27 CET <Nazell17325> 夜談さんがKORO-SUZO見てる ほんとKANA-DEROで歌ってたあのでろーんはどこへ
1089074409938120705 2019-01-26 09:15:48 CET <T_sasimi> KANA-DEROから2週間か…そうか…
1089060537516810240 2019-01-26 08:20:40 CET <TokkeyU> 来月はKANADERO物販買うし、トランペット買うしでお金飛んじゃうな… トランペット買ったらまず吹いてみたいのはコンギョ
1089024113308401666 2019-01-26 05:55:56 CET <TW_YUG2434> こんなに血にまみれてたっけ、KANADERO
1088986399389302784 2019-01-26 03:26:04 CET <okotaruhito> KANA-DERO前夜祭  https://youtu.be/_KLgS9Jgzas  @YouTubeさんから
1088958517128527873 2019-01-26 01:35:17 CET <alice_dirt> これヤバすぎやで  樋口楓1stライブ「KANA-DERO」ライブ映像特別公開！『響鳴』  https://youtu.be/NcaGIXz6fdI  @YouTubeさんから
```

**Comment by debugzxcv** [comment]
That's strange. Last time run the cmd only get 4 tweets, but now get 68 tweets.

**Comment by pielco11** [comment]
There might be various reasons, but yes, that's strange

I would like to keep this PR open for the next few days a keep monitored the issue, if you find other accounts or want just to update me with your findings, just feel free to comment!

I did not do checks, yet. But why did you change the code in that way? I'm not saying that there's something wrong, I did not reviewed it yet, I'm just asking about how that solved the issue in your previous situations
-------- Messaggio originale --------
On 5 Feb 2019, 21:35, debugzxcv ha scritto:

**Comment by debugzxcv** [comment]
I just trace twitter search web in my previous situations. Here is my finds: 

> [To retrieve Tweets further back in time, use the value of `min_position` found in the current response as the `max_position` parameter in the next call to this endpoint.](https://developer.twitter.com/en/docs/tweets/curate-a-collection/api-reference/get-collections-entries)

so if max_position == response['min_position'] no more tweets
[test script](https://gist.github.com/debugzxcv/876f55aaaba8cf8b1dba0656a368179e)

**Pull request closed without merging**
