### PR TITLE
Proposal: Make Config a @dataclass

### PR DESCRIPTION
**Pull request by LinqLover**
One of all the advantages of data classes is you can construct them in one line without retyping every property:

```python3
import twint
c = twint.config.Config(Limit=42, Search='twint', Lang='en')
```

### CODE REVIEW

**Comment by pielco11** [comment]
This would break a few custom scripts of users, but it's a great idea so I'd suggest to possibility (if not already in place) to use both the `DataClass` solution and the one in "dot notation"... wdyt?

**Comment by LinqLover** [comment]
What exactly would this break? :-) As far as I can see you can still use the classical dot notation when working with the dataclass object.

**Comment by pielco11** [comment]
Honestly idk, so I thought to ask. Confirm that it works, thanks for your contribution!

**Comment by LinqLover** [comment]
Great, thanks for the fast review!

**Pull request merged**
