### PR TITLE
Added: possibility to pass callback to Search() function.

### PR DESCRIPTION
**Pull request by im-n1**
This solves #362. I have added a small modification which enables to pass a callback called once the `Twint.main()` job is done.

It's tested and works well. See bellow the `A` is printed once the scrapping is finished.

image

The loop issue is not really an issue. It's jupyter's bug.

### CODE REVIEW

**Comment by pielco11** [comment]
Looks like one has to pass `lambda x : function(args)` always

May you implement callbacks for the other functions? So that every function will handle callbacks and so will have the same "potentiality"

**Comment by im-n1** [comment]
No, callback is optional. You can use the `Search` function without callback parameter.

I would like to but I'm short of time. Maybe you can merge this and when time advances we can work on the rest.

**Comment by pielco11** [comment]
Sorry, I meant that `lambda x:` needs to be passed always and not only `function(args)`

I'll merge this and leave it open to remind that other functions needs this feature

**Comment by pielco11** [comment]
#373

**Comment by im-n1** [comment]
I see. The thing is you pass callable with one argument. The argument is mandatory and it's output of the finished task (which is None in this case). So you can use it like:

```python
twint.run.Search(c, lambda task_output: my_other_function("my parameter"))
```

or

```python

def my_other_function(task_output):
    pass

twint.run.Search(c, my_other_function)
```

**Pull request merged**
