### PR TITLE
Adding language to tweet metadata

### PR DESCRIPTION
**Pull request by jomorrcode**
This adds the language of the tweet (pulled from the html) to the tweet metadata by adding the attribute t.lang to the Tweet object, as well as updating write_meta.py and format.py to allow for saving.

### CODE REVIEW

**Comment by pielco11** [comment]
Great! Would also be possible to update the schema for Elasticsearch, Database and Panda? The concept is the same.

## For Elasticsearch
- edit `createIndex` function (`lang` would need to be `keyword`, see `hashtag` as an example)
- edit `Tweet` function

## For Database
- edit the tweets' table schema in the `init` function
- edit `tweets` function, don't forget to add a `?`

## For Pandas
- edit `update` function

**Comment by jomorrcode** [comment]
Will do.    I knew there were probably other places in the code that needed this added but wasn't sure where!

**Comment by jomorrcode** [comment]
I apologize, I have been insanely busy with work and trying not to code in my free time...  I will try to get to this this week though.

**Comment by jomorrcode** [comment]
Okay Francesco,  I THINK I've done all this successfully.    You may want to look at the elasticsearch and database changes just to make sure I didn't screw that up.

**Comment by pielco11** [comment]
Seems nice to me

**Pull request merged**
