### PR TITLE
Make it possible to use as command

### PR DESCRIPTION
**Pull request by tkmru**
This make it possible to use as `twint` command. It will be more useful.

### CODE REVIEW

**Comment by pielco11** [comment]
Is this cross-platform?

**Comment by tkmru** [comment]
I used [scripts](https://docs.python.org/3/distutils/setupscript.html#installing-scripts) keyword in setuptools for using as command. It will work in cross-platform.

**Comment by haccer** [comment]
Thanks @tkmru! This is a good idea. Can you make changes to `Twint.py` and `setup.py` so we're using `entry_points` instead of `scripts`?

**Comment by tkmru** [comment]
`Twint.py` is not included in twint package, I think it is difficult to specify `entry_points`. Is not it good to use `scripts`?

**Comment by tkmru** [comment]
@haccer I moved `Twint.py` into the package, changed to use `entry_points` instead of `scripts`.

**Comment by haccer** [comment]
Alright, I will probably won’t be available to verify this until next Sunday. 

@pielco11, before merging can you make sure the behavior works as intended. Thanks.

**Comment by pielco11** [comment]
It seems to be working as command but not via CLI since `main()` is not called.
I did not try with other OS than Ubuntu, yet.

**Comment by tkmru** [comment]
sorry.

But is it necessary to use it as a single script from the CLI? It can be used as a command.
twint package is imported in `twint.py`, it is difficult to solve the path dependency.

If you want to be compatible with both being usable as a command and working as a standalone script, it is better to move `twint.py` outside twint directory and use scripts instead of entry_points.

**Comment by pielco11** [comment]
A little change that me and another member were talking about is: why not use some imports in twint/twint.py instead of importing the entire module? It's more "package-consistent". Plus importing the entire module will import twint.py itself, which is not needed.

Also we propose to change `twint/twint.py` to `twint/cli.py` to make the name more consistent

Plus this needs to be changed as well 
https://github.com/twintproject/twint/blob/ea8b6780f4ee8ae8512cd42c3893d4bb3816c1a0/twint/twint.py#L111
`twint` instead of `Twint.py` since the first will be the entry-point

**Comment by haccer** [comment]
I had fun testing this. I think this is fine to `Squash and merge`. Thoughts @pielco11?

**Comment by haccer** [comment]
Thank you @tkmru!

**Comment by jvanalst** [comment]
The error message is wrong when you run it through the CLI, FYI.

```
vanalsti@~$ twint -s "Donald Trump" --verified --users
usage: python3 twint [options]
twint: error: unrecognized arguments: --users
```

Not sure why --users isn't recognized since it's in the examples, but it really shouldn't be telling me to use "python3 twint".

**Comment by pielco11** [comment]
The error message is correct, `--users` does not exist. The arguments available for user(s) are: `--username`, `--userlist` and `--user-id`
-------- Messaggio originale --------
On 20 Nov 2018, 18:07, Jeffrey D. Van Alstine ha scritto:

**Comment by jvanalst** [comment]
I opened a new issue to deal with the users flag, since I don't want to derail this on.

Still twint CLI shouldn't be telling users to user python3 twint.

**Pull request merged**
